version: '3.4'

services:
  torrxfer-server:
    image: sushshring/torrxfer-server
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./trial/transfer:/transfers
    entrypoint: ["/bin/torrxfer-server", "--debug"]
    ports:
      - 9650:9650
  torrxfer-client:
    image: sushshring/torrxfer-client
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./trial/config.json:/config/client.json
      - ./trial/watch:/transferwatch
    environment:
      - TORRXFER_CLIENT_DEBUG=true
    depends_on:
      - torrxfer-server
