name: Docker
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'

env:
  # TODO: Change variable to your image's name.
  SERVER_IMAGE_NAME: torrxfer-server
  CLIENT_IMAGE_NAME: torrxfer-client

jobs:
  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    -
        name: Docker server meta
        id: servermeta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            sushshring/torrxfer
            ghcr.io/torrxfer/torrxfer-server
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
    -
        name: Docker client meta
        id: clientmeta
        uses: crazy-max/ghaction-docker-meta@v2
        with:
          # list of Docker images to use as base name for tags
          images: |
            sushshring/torrxfer-client
            ghcr.io/torrxfer/torrxfer-client
          # generate Docker tags based on the following events/attributes
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
    -
      name: Build and push server
      uses: docker/build-push-action@v2
      with:
        context: .
        target: $SERVER_IMAGE_NAME
        platforms: linux/amd64,linux/arm64,linux/arm/v7 
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.servermeta.outputs.tags }}
        labels: ${{ steps.servermeta.outputs.labels }}
    -
      name: Build and push client
      uses: docker/build-push-action@v2
      with:
        context: .
        target: $CLIENT_IMAGE_NAME
        platforms: linux/amd64,linux/arm64
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.clientmeta.outputs.tags }}
        labels: ${{ steps.clientmeta.outputs.labels }}

