name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    - name: Build Client
      run: go build -v -o bin/torrxfer-client ./cmd/client
    - name: Build Server
      run: go build -v -o bin/torrxfer-server ./cmd/server
    - name: Test
      run: go test ./...